stages:
  - test

test:
  stage: test
  script:
  # Simple request generator, no 3rd party services involved
  - apt-get update -qy
  - apt-get install -y python3-dev python3-pip
  - pip3 install -r requirements.txt
  - pytest